### ISSUE TITLE
style selectors:  doesn't support  nesting pseudo selectors

### ISSUE THREAD

**Issue by X-Jagger** [vanilla-extract-css/vanilla-extract#1068]
### Describe the bug

I'm new to [vanilla-extract](https://github.com/vanilla-extract-css/vanilla-extract) ,and when I use it with selectors, I encountered a problem, which it didn't work as I thought, I tried to search the website, but I didn't find any words to say I can't use it like this.

I'm not sure whether is a bug or feature

### not working
![image](https://user-images.githubusercontent.com/23659716/232695469-dbe68682-aae4-41f1-b84f-69bea793f26c.png)

### working 
![image](https://user-images.githubusercontent.com/23659716/232695630-5c7cde4b-0504-4891-8086-20ac0a96fac8.png)

### Reproduction

https://vanilla-extract.style/

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 92.42 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 108.0.2
    Safari: 15.1
  npmPackages:
    @vanilla-extract/css: ^1.11.0 => 1.11.0 
    @vanilla-extract/vite-plugin: ^3.8.0 => 3.8.0 
    vite: ^4.2.0 => 4.2.
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by X-Jagger** [comment]
I searched such question with gpt-4, it somehow answered my question, (Need confirmation)
![image](https://user-images.githubusercontent.com/23659716/232698577-37f10ba1-2208-4351-846f-97590e132bae.png)

**Comment by askoufis** [comment]
> I searched such question with gpt-4, it somehow answered my question, (Need confirmation) 

GPT-4's response is pretty accurate. Not supporting nested selectors in an intentional decision, though that doesn't mean we will never support it in the future. Given that native CSS is starting to support [CSS nesting](https://developer.chrome.com/articles/css-nesting/), it could make sense to support it in Vanilla Extract in the future.

Generally speaking, Vanilla Extract's docs are quite explicit about what _is_ supported, and the types will help you avoid situations that are _not_ supported.
