### ISSUE TITLE
::before selector "crashing" the CSS for the builded application, with next 13.4

### ISSUE THREAD

**Issue by matheussartori** [vanilla-extract-css/vanilla-extract#1083]
### Describe the bug

I have a styled div with the ::before selector, and when I'm running the development script on next.js, it's working fine.

```ts
export const mobileMenuContainer = style({
  '@media': {
    'screen and (min-width: 992px)': {
      display: 'none'
    }
  },

  selectors: {
    '&::before': {
      content: '',
      borderLeft: `1px solid ${vars.color.border}`,
      position: 'relative',
      bottom: 8,
      marginLeft: 8,
      marginRight: 6
    }
  }
})
```

The result is:

![image](https://user-images.githubusercontent.com/20970237/236701209-e9243861-baeb-4bda-afba-10f2d7e658a3.png)

When i build the application, and start with the `npm start` script, this is the result:

![image](https://user-images.githubusercontent.com/20970237/236701232-82e3c922-8b72-4f9b-bf1e-1bda286e05a4.png)

Apparently, only my global styles are working. Every component styled with the `style` method, don't have the CSS bundled on the final version. If i remove the before selector, works fine.

Obs: I've already tried, instead of using the '::before' inside the selectors key, using directly, and already tried using `:before` as well.

Maybe it's something that I'm doing wrong, but I'm not sure yet.

### Reproduction

https://github.com/matheussartori/portfolio/tree/vanilla-extract-before-bug

Branch: vanilla-extract-before-bug

File that has the ::before selector: src/components/menu/MobileMenu/mobileMenu.css.ts

Just running npm build and npm start, you can reproduce the bug. If you run npm run dev, the bug won't happen.

### System Info

```shell
I'm using PopOS 22.04 LTS, chrome in the latest version (115.0.5750.0), with node v18.16.0, and npm 9.6.5
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rothsandro** [comment]
The problem is not related to the `::before` selector but to some import and/or server component / client component problem I guess. Remove the `vars` import from your `mobileMenu.css.ts` and it works.

The layout component has a direct dependency on ThemeProvider but the ThemeProvider is also imported because of dependencies below. This somehow breaks the styling. If you extract the theme context into its own file, so that `useTheme` only depends on the context file but not on `ThemeProvider` it works.

```
layout --> header --> themeSwitch --> useTheme --> ThemeProvider 
```

**Comment by matheussartori** [comment]
> The problem is not related to the `::before` selector but to some import and/or server component / client component problem I guess. Remove the `vars` import from your `mobileMenu.css.ts` and it works.
> 
> The layout component has a direct dependency on ThemeProvider but the ThemeProvider is also imported because of dependencies below. This somehow breaks the styling. If you extract the theme context into its own file, so that `useTheme` only depends on the context file but not on `ThemeProvider` it works.
> 
> ```
> layout --> header --> themeSwitch --> useTheme --> ThemeProvider 
> ```

Yeah, this was caused by the `vars` import, as you said. I changed some things on the theme provider and now it's working. Thank you.
