### ISSUE TITLE
Sprinkles not applying in production build with NextJS App Directory

### ISSUE THREAD

**Issue by zackshackleton** [vanilla-extract-css/vanilla-extract#1085]
### Describe the bug

Once sprinkles reach a certain size, NextJS production builds no longer import the needed CSS files. While running in development mode, everything works great.

I have created a minimal reproduction of the issue. If you go in and comment out any 1 of the sprinkle conditions in `./src/styles/sprinkles.css.ts` the production build works correctly. 

When the styles are not applied I am seeing the correct classnames in the mark up and the correct css generated in `./.next/static/css/*` however the css files are not being loaded.

I made the page and layout client components to avoid any possible issues with Next's server components.

Dev Build:
<img width="582" alt="Screenshot 2023-05-09 at 2 30 16 PM" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/13963847/eba52c48-17e2-4c1e-b22b-f0dba4f53b32">

Production Build:
<img width="582" alt="Screenshot 2023-05-09 at 2 30 43 PM" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/13963847/f1995dbd-c066-4323-9591-b4a936d07d61">

### Reproduction

https://github.com/zackshackleton/sprinkles-nextjs13

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.20 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.5 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    @vanilla-extract/css: ^1.11.0 => 1.11.0
    @vanilla-extract/next-plugin: ^2.1.2 => 2.1.2
    @vanilla-extract/sprinkles: ^1.6.0 => 1.6.0
    @vanilla-extract/webpack-plugin: ^2.2.0 => 2.2.0
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by prncss-xyz** [comment]
Same problem encontered.

**Comment by anthony-kirkham** [comment]
Same issue encountered also

**Comment by zxqx** [comment]
Seeing the same thing.

**Comment by zxqx** [comment]
Seeing the same issue w/ production build and agree it seems like it's related to how many sprinkles are being extracted.

**Comment by adri1wald** [comment]
I've been hunting this down for the last couple hours. What I've found is the following:

https://github.com/vercel/next.js/blob/v13.4.2/packages/next/src/server/app-render/get-css-inlined-link-tags.tsx

`cssFilesForEntry` has the missing chunks, but for some reason the `chunks` set that gets returned does not. Now trying to figure out why that is the case.

**Comment by mattcompiles** [comment]
This looks like an issue on the Next side. I'd suggest creating an issue on the Next repo. We can keep this open until it's resolved though.

**Comment by zackshackleton** [comment]
Sounds good, just created an [issue](https://github.com/vercel/next.js/issues/49817) over with Next.

**Comment by sebpowell** [comment]
Just ran into this as well – I believe it's the same issue – locally, I am seeing class names such as `sprinkles_paddingLeft_gutter_mobile__3c6yu8e6` in the DOM. In production, this shows up as `_3c6yu8e6`, but is not linked to any stylesheet.

**Comment by z4o4z** [comment]
looks like i've found a workaround:

needs to disable `splitChunks` in the `next.config.js`:
```js
  {
    webpack: config => {
      config.optimization.splitChunks = false;

      return config;
    },
  }
```

**Comment by sebpowell** [comment]
@z4o4z – this worked for me, thank you for sharing!

**Comment by jere-co** [comment]
@z4o4z Excellent find. 

This seems to not be a sprinkles-specific issue, but rather breaks down when the amount of CSS is large enough. 

I created [a test repository](https://github.com/jere-co/vanilla-extract-app-dir) for demonstration. 

[This commit](https://github.com/jere-co/vanilla-extract-app-dir/commit/2667c75b6f7ba04e0e470045d0371ab43ecb3ff3) breaks the build, as does uncommenting any more of the style objects currently commented out in the `src/app/styles.css.ts`. 

Like @z4o4z described, setting the `webpack config.optimization.splitChunks` in `next.config.js` to `false` makes the build work again ([latest commit in the above repository](https://github.com/jere-co/vanilla-extract-app-dir/commit/6cce2f3116ef34e81003304fc1c0370cc155777e)).

**Comment by i-bsd** [comment]
> yeah, it looks like the issue is related to [mini-css-extract-plugin](https://www.npmjs.com/package/mini-css-extract-plugin) cause it generates chunks and files. I have an idea in mind how to disable chunks only for CSS, will try and let you know if that works.

Thanks. The splitChunks workaround works but it's not a solution if it hurts performance causing large bundles.

**Comment by vovacodes** [comment]
We've run into the same issue, the workaround also works so thanks @z4o4z . Hoping that a long-term fix is landing some time soon

**Comment by vovacodes** [comment]
Well this workaround has a severe drawback of bloating the size of the lambdas that next creates for your server components, and we actually ran into the limit (50MB❗️) there.

This idea about the fix you had @z4o4z, is it something that we could maybe do locally via the next.config's webpack hook?

**Comment by elliotwestlake** [comment]
Not sure if this has been fixed but we are using `next@13.4.4` and `@vanilla-extract/next-plugin@2.1.3` and I have just removed this and all seems to be working fine now!

**Comment by QuentinRoy** [comment]
It might depend on the size of your css. I have just tried it again with `next@13.4.5` and `@vanilla-extract/next-plugin@2.1.3`, and no luck..

**Comment by zackshackleton** [comment]
This issue seems to be resolved with the latest Vanilla Extract and Next builds

**Comment by headline-design** [comment]
Using the latest Vanilla Extract and Next 14 and it's still a major issue.

**Comment by askoufis** [comment]
@headline-design Please create a new issue with a reproduction if you're still encountering this issue.

**Comment by dlepaux** [comment]
Please check this workaround: https://github.com/vercel/next.js/issues/53858#issuecomment-1911801564
It works like a charm :fire:
