### ISSUE TITLE
Next.js 13 - `experimental.appDir` still being used in stable App Router

### ISSUE THREAD

**Issue by exneval** [vanilla-extract-css/vanilla-extract#1087]
### Describe the bug

Need follow up patch related to PR #1060 after [App Router being stable.](https://nextjs.org/blog/next-13-4)

Need help @markdalgleish  @SuttonJack 

[Reference discussion](https://github.com/vanilla-extract-css/vanilla-extract/issues/929#issuecomment-1538555608)

### Reproduction

https://github.com/SuttonJack/vanilla-extract-app-dir

### System Info

```shell
Windows 11
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mattcompiles** [comment]
We're going to follow up with the Next team about how to deal with these issues going forward. We're having to reach into private Next internals to make VE work currently which is the cause of these issues. 

Will report back once they've responded.
