### ISSUE TITLE
The part selector is not supported.

### ISSUE THREAD

**Issue by BugMaker-Huang** [vanilla-extract-css/vanilla-extract#1103]
### Describe the bug

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/120626393/838a748a-d677-4582-b19e-45d190a4e9a3)

### Reproduction

selectors: {     '&::part(external-wrapper)': {}   }

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 133.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.6.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 15.2
  npmPackages:
    @vanilla-extract/css: ^1.11.0 => 1.11.0
```

### Used Package Manager

pnpm

### Logs

```shell
[
  'Build failed with 1 error:\n' +
    'node_modules/.pnpm/registry.npmmirror.com+@vanilla-extract+css@1.11.0/node_modules/@vanilla-extract/css/dist/transformCss-072727cc.cjs.dev.js:163:10: ERROR: [plugin: vanilla-extract-plugin-uncached] Invalid selector: ::part(external-wrapper)'
]
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rothsandro** [comment]
The `css-what` package needs to be updated. This has been fixed in v6.1.0, see https://github.com/fb55/css-what/issues/761
