### ISSUE TITLE
Can't get started with @vanilla-extract/css on a basic Hello World

### ISSUE THREAD

**Issue by kyplerdeloitte** [vanilla-extract-css/vanilla-extract#1135]
### Describe the bug

I am unable to assign the styles (background: red) I created with "import {styles} from vanilla-extract/css" to a simple div with the text "Hello World". I tried using different bundler integrations (vite, webpack, gatsby and bagel) but I keep getting this same error:

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/113994597/6efc3e46-3888-47d5-a128-091d4143bb95)

Anyone have any idea why? been stuck on this problem for almost a week and would love to get started.

### Reproduction

https://github.com/kyplerdeloitte/hello-world

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 3.59 GB / 15.71 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\node_modules\.bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vanilla-extract/babel-plugin: ^1.2.0 => 1.2.0
    @vanilla-extract/css: ^1.12.0 => 1.12.0
    @vanilla-extract/vite-plugin: ^3.8.2 => 3.8.2
    @vanilla-extract/webpack-plugin: ^2.2.0 => 2.2.0
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by janbiasi** [comment]
@kyplerdeloitte I think you should probably open the issue on the [gatsby-plugin-vanilla-extract](https://github.com/gatsby-uc/plugins/tree/main/packages/gatsby-plugin-vanilla-extract) for the gatsby integration. 

The other starter guides with official integration (tested Vite, Next & Webpack) work as expected, you may also want to check my recent repro repo for another issue which uses VE + Next.js: https://github.com/janbiasi/repro-next-vanilla-extract-jest

**Comment by janbiasi** [comment]
I'd recommend to just follow the [Getting Started - Bundler Integration](https://vanilla-extract.style/documentation/getting-started/#bundler-integration) guide on the website, that's the easiest way. If you still don't get it to work hit me up and I can provide you an example repo 😃
