### ISSUE TITLE
When developing with Next.js, css is not generated

### ISSUE THREAD

**Issue by Karibash** [vanilla-extract-css/vanilla-extract#1152]
### Describe the bug

When a page transition is made on the Next.js development server, the css of the destination page is not generated.
Reproduced with version 2.2.1 of @vanilla-extract/next-plugin, lowering the version to 2.1.3 makes it work correctly.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-dcvpht

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.16 GB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.16.0 - ~/.local/share/nvm/v18.16.0/bin/node
    npm: 9.5.1 - ~/.local/share/nvm/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.248
    Firefox: 81.0.2
    Safari: 16.5.2
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edenstrom** [comment]
I've been looking into this a bit. It only happens between navigation in the `pages` directory. Navigating in the `app` directory works perfectly. Also navigating from a route in `app` to a route in `pages` and vice versa.

One more thing is that HMR doesn't work either.

1. Go to home
2. Change index.css.js (CSS is updated)
3. Navigate to other
4. Change other.css.js (CSS is not updated)
5. Refresh
6. CSS is loaded and HMR works again

No solution in sight though. Trying to debug further.

Possible culprit? https://github.com/vanilla-extract-css/vanilla-extract/pull/1105

**Comment by hazzo** [comment]
Same here, pls fix this :)

**Comment by syfxlin** [comment]
The cause of the problem is that @vanilla-extract/next-plugin removed the next-style-loader from https://github.com/vanilla-extract-css/vanilla-extract/pull/1105. However, using the [next- style-loader](https://github.com/vercel/next.js/blob/6e5b935fd7a61497f6854a81aec7df3a5dbf61ac/packages/next/src/build/webpack/config/blocks/css/loaders/client.ts#L16-L42) may cause inconsistent order between the development and production CSS outputs. I'm not sure if it can be added back.

**Comment by IwannabeRealnerD** [comment]
I had exactly same issue. - On page directory, css was not generated on HTML(development server)

I downgraded @vanilla-extract/next-plugin to 2.1.2(it was 2.3.1) and it's working fine.
Build result is also working fine.

NextJS - 13.3.4
@vanilla-extract/css - 1.13.0

**Comment by huypham50** [comment]
Same issue, hopefully https://github.com/vanilla-extract-css/vanilla-extract/pull/1203 fixes this
```
"next": "^14.0.4"
"@vanilla-extract/css": "^1.13.0"
"@vanilla-extract/next-plugin": "^2.1.2"
```

**Comment by askoufis** [comment]
I tested [`@vanilla-extract/next-plugin@2.4.0`](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fnext-plugin%402.4.0) in your reproduction and it has fixed the issue.

**Comment by takahiro-1227** [comment]
I upgrade to 2.4.0, but this issue is still happened.

**Comment by askoufis** [comment]
@takahiro-1227 Could you please raise a separate issue with a minimal reproduction.
