### ISSUE TITLE
@vanilla-extract/integration compiler generate "border" at ci envrionment

### ISSUE THREAD

**Issue by cqh963852** [vanilla-extract-css/vanilla-extract#1162]
### Describe the bug

We are using vanilla-extract create a css component library.

With vitest framework, And The snapshot generated locally is correct.

But in the ci environment, there will be more “border” attributes

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/17702287/3704bb1a-1c6e-47f7-be97-a50c0a2fd0a4)

But the button css doesn't has border props

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/17702287/13e5e365-ea9d-4dff-9a55-c6882b5e80bf)

### Reproduction

https://github.com/idealjs/camphora/actions/runs/5847174374/job/15853163192

### System Info

```shell
Github ci
```

### Used Package Manager

yarn

### Logs

```shell
RUN  v0.34.1 /home/runner/work/camphora/camphora/packages/camphora-styled

 ❯ src/__test__/snapshot.test.ts  (1 test | 1 failed) 1007ms
   ❯ src/__test__/snapshot.test.ts > button
     → Snapshot `button 2` mismatched

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/__test__/snapshot.test.ts > button
Error: Snapshot `button 2` mismatched

- Expected
+ Received

  ".button_button__1ph4cad6 {
    cursor: pointer;
    display: inline-flex;
    flex-shrink: 0;
    align-items: center;
    justify-content: center;
    text-align: center;
    height: 48px;
    min-height: 48px;
    padding: 0px 16px 0px 16px;
    border-radius: var(--rounded-btn__92wzfbr);
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    transition: background-color 0.2s ease-in-out;
+   border: none;
  }
  .button_button__1ph4cad6:active, .button_button__1ph4cad6.button_buttonActive__1ph4cad0 {
    transform: scale(0.95);
  }
  .button_button__1ph4cad6.button_buttonPrimary__1ph4cad1 {
    background-color: var(--colors-primary-bg__92wzfb4);
    color: var(--colors-primary-content__92wzfb6);
  }
  .button_button__1ph4cad6.button_buttonPrimary__1ph4cad1:hover {
    background-color: var(--colors-primary-focus__92wzfb5);
  }
  .button_button__1ph4cad6.button_buttonNeutral__1ph4cad2 {
    background-color: var(--colors-neutral-bg__92wzfbd);
    color: var(--colors-neutral-content__92wzfbf);
  }
  .button_button__1ph4cad6.button_buttonNeutral__1ph4cad2:hover {
    background-color: var(--colors-neutral-focus__92wzfbe);
  }
  .button_button__1ph4cad6.button_buttonSecondary__1ph4cad3 {
    background-color: var(--colors-secondary-bg__92wzfb7);
    color: var(--colors-secondary-content__92wzfb9);
  }
  .button_button__1ph4cad6.button_buttonSecondary__1ph4cad3:hover {
    background-color: var(--colors-secondary-focus__92wzfb8);
  }
  .button_button__1ph4cad6.button_buttonAccent__1ph4cad4 {
    background-color: var(--colors-accent-bg__92wzfba);
    color: var(--colors-accent-content__92wzfbc);
  }
  .button_button__1ph4cad6.button_buttonAccent__1ph4cad4:hover {
    background-color: var(--colors-accent-focus__92wzfbb);
  }
  .button_button__1ph4cad6.button_buttonGhost__1ph4cad5 {
    background-color: transparent;
    color: currentcolor;
  }
  .button_button__1ph4cad6.button_buttonGhost__1ph4cad5:hover {
    background-color: color-mix(in srgb, var(--colors-base-content__92wzfb3) var(--opacity-btn__92wzfbo), #fff0);
  }"

 ❯ src/__test__/snapshot.test.ts:24:15
     22|     export var button = 'button_button__1ph4cad6';"
     23|   `);
     24|   expect(css).toMatchInlineSnapshot(`
       |               ^
     25|     ".button_button__1ph4cad6 {
     26|       cursor: pointer;

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

  Snapshots  1 failed
 Test Files  1 failed (1)
      Tests  1 failed (1)
   Start at  12:05:51
   Duration  1.52s (transform 72ms, setup 0ms, collect 217ms, tests 1.01s, environment 0ms, prepare 99ms)

Done in 2s 279ms
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@cqh963852 Looking at the `button.css.ts` file now, I see [there is a `border: none` style](https://github.com/idealjs/camphora/blob/16647663d04b67ba73461a1f556f86d654625892/packages/camphora-styled/src/button.css.ts#L38). Maybe your local snapshot was generated before [this PR](https://github.com/idealjs/camphora/pull/25) was merged?

More generally, what is the intention of this test? You're basically testing that the Vanilla Extract compiler works correctly, separate from whatever integration you're using (e.g. vite). There are already tests for this - they are inside the Vanilla Extract repo. You, as a consumer of the integration, shouldn't have to worry that the integration works correctly - that's the job of the maintainers of the package.

**Comment by cqh963852** [comment]
@askoufis 
Thanks a lot for help.

> More generally though, what is the intention of this test?

I added this test to avoid breaking changes that would cause visual changes.
After modifying the related component style, we need to check the corresponding snapshot. 
Currently, it is only a code snapshot. In the future. We will prepare to add an image snapshot.

Do you have testing suggestions for component libraries?

**Comment by askoufis** [comment]
Image snapshots will be much more useful in the long term if you want to prevent visual regressions. CSS snapshots don't _really_ help to spot visual changes, you're really just testing that the styles you wrote generate the correct CSS (again, we're already testing this for you). You don't even have components yet, so you're not even testing that the components are correctly using the CSS at all.

Also, the hashes of the classnames will change, so that's just more time spent updating snapshots that aren't really testing anything.
