### ISSUE TITLE
`defineProperties` Error: No overload matches this call 

### ISSUE THREAD

**Issue by jtabalujan2** [vanilla-extract-css/vanilla-extract#1181]
### Describe the bug

Haven't been able to correctly setup `vanilla-extract/sprinkles` because TS fails to be able to match any of the properties expected in the `defineProperties` function.

Also reproduced on a local repo with a fresh repo of NextJS 13 and no other dependencies installed.

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ conditions: { mobile: {}; tablet: { '@media': string; }; desktop: { '@media': string; }; }; defaultCondition: string; }' is not assignable to parameter of type 'UnconditionalAtomicOptions<AtomicProperties>'.
      Object literal may only specify known properties, and 'conditions' does not exist in type 'UnconditionalAtomicOptions<AtomicProperties>'.ts(2769)
```

### Reproduction

Copied the exact code given in the docs for [conditions ](https://vanilla-extract.style/documentation/packages/sprinkles/#conditions)

https://www.typescriptlang.org/play?ts=5.1.6#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUAUoRiqzCoDOcAvnOgSHAEQACAbgIZbAA2XbAtKgAeMKGwDGMAPRkwUbAGsu5BgG4AUGrEQsZeLMLEYpCgF4UGbHgJES5ABQI1cOFqzJgR7WQBciJ87gQCAAjblRfBEoAGn9nGDZgpRgIuAByJhBUdzZU31SyMShUVCw4DmQ4OxBsPgB3YGQYAAtfAHYANgAOMEEASlSqGIDzMnkYQhT0zOzctIKikrK3SuqsOobm3wBGAAYAJgAWHv6qf2j-NHQ2AFcuGABhbXdPLDyg0KVUmMpeoA

### System Info

```shell
N/A
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mc-petry** [comment]
In your example you have not defined any properties, try adding `properties: {}`:
```ts
import { defineProperties } from "@vanilla-extract/sprinkles";

const properties = defineProperties({
  conditions: {
    mobile: {},
    tablet: { '@media': 'screen and (min-width: 768px)' },
    desktop: { '@media': 'screen and (min-width: 1024px)' }
  },
  defaultCondition: 'mobile',
  properties: {
    ...
  }
})
```

**Comment by jtabalujan2** [comment]
Thanks @mc-petry looks like I am misunderstanding how to use Sprinkles to begin with 😄
