### ISSUE TITLE
vanilla set wrong css name in Remix run

### ISSUE THREAD

**Issue by WreewanMorhee** [vanilla-extract-css/vanilla-extract#1189]
### Describe the bug

<img width="645" alt="Screen Shot 2023-09-21 at 4 00 30 PM" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/33398071/c68cb40c-f49a-424a-86c8-be5e357e752b">

Notice that !?
in the dom, the className is style__ContentBoard
but the actual applied name is style__Img

why this happened

### Reproduction

no

### System Info

```shell
"@remix-pwa/push": "*",
		"@remix-run/css-bundle": "^1.19.3",
		"@remix-run/express": "^1.19.3",
		"@remix-run/node": "^1.19.3",
		"@remix-run/react": "^1.19.3",
		"@remix-run/serve": "^1.19.3",
		"@vanilla-extract/css": "^1.13.0",
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
Could you include more of the devtools in the screenshot? This doesn't really seem like an issue with Vanilla Extract or Remix. I don't think it's possible for an element to have a classname attached but to show up with a different name in the devtools.

What are the definitions of the `ContentBoard` and `Img` styles in your code?

**Comment by askoufis** [comment]
@WreewanMorhee Closing this issue for now. If you're still encountering this issue and have any more information about it/a reproduction, feel free to re-open.
