### ISSUE TITLE
Can't set `font-display` CSS property

### ISSUE THREAD

**Issue by twharmon** [vanilla-extract-css/vanilla-extract#1223]
### Describe the bug

When you add [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#browser_compatibility), you get this error
> Argument of type '{ fontDisplay: string; }' is not assignable to parameter of type 'GlobalStyleRule'.
  Object literal may only specify known properties, and 'fontDisplay' does not exist in type 'GlobalStyleRule'.ts(2345)

### Reproduction

N / A

### System Info

```shell
System:
    OS: Linux 6.5 Fedora Linux 39 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 21.45 GB / 27.10 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.8.1 - /usr/bin/node
    npm: 10.1.0 - /usr/bin/npm
  npmPackages:
    @vanilla-extract/css: ^1.13.0 => 1.13.0 
    @vanilla-extract/css-utils: ^0.1.3 => 0.1.3 
    @vanilla-extract/vite-plugin: ^3.9.0 => 3.9.0 
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
This is because `font-display` is specific to `@font-face` rules. Using `fontDisplay` won't work with `style` or `globalStyle`. You want to use either the [`fontFace`](https://vanilla-extract.style/documentation/api/font-face/) or [`globalFontFace`](https://vanilla-extract.style/documentation/global-api/global-font-face/) APIs.
