### ISSUE TITLE
`@vanilla-extract/css` only work with pnpm!

### ISSUE THREAD

**Issue by raphaelboukara** [vanilla-extract-css/vanilla-extract#1225]
### Describe the bug

This [commit](https://github.com/vanilla-extract-css/vanilla-extract/commit/1dbd56c8292af03e53aa3f4b288a40d88bc762cf#diff-c3b75a0385d65930617f260732fb419cd271f4f79fb3eac1fb99ea88f07e8da1R119) migrate from `ahocorasick` to `modern-ahocorasick` without majoring `@vanilla-extract/css`.

However, this change is a breaking change since from those changes, `pnpm` [is required to install](https://github.com/sonofmagic/modern-ahocorasick/blob/v1.0.0/package.json#L21) `modern-ahocorasick`, means now **vanilla-extract became available only for people that use `pnpm`**.

> [!warning]
> By chance, because of this npm issue: https://github.com/npm/cli/issues/2660, the script that check `pnpm` presence won't work, but if you are using for instance `node 14` and `npm`: **install will fail**.
> When this issue will be fixed, all people that installed `vanilla-extract` with `npm` will be affected.

>[!note]
> To reproduce:
> ```
> $ git clone git@github.com:raphaelboukara/ahocorasick.git
> $ cd ahocorasick
> $ nvm use
> $ npm i
> ```

### Reproduction

https://github.com/raphaelboukara/ahocorasick

### System Info

```shell
System:
  OS: macOS 13.4.1
  CPU: (10) x64 Apple M2 Pro
  Memory: 419.46 MB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
  npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
Browsers:
  Chrome: 119.0.6045.123
  Safari: 16.5.2
```

### Used Package Manager

npm

### Logs

```shell
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
║   For more details, go to https://pnpm.js.org/              ║
║                                                             ║
╚═════════════════════════════════════════════════════════════╝
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
I think the upstream package probably shouldn't use `only-allow` in a `preinstall` script as it was probably meant to only be used in apps rather than packages. I have made a PR upstream https://github.com/sonofmagic/modern-ahocorasick/pull/11. If that isn't merged soon, we'll revert the change.

**Comment by sonofmagic** [comment]
`modern-ahocorasick@1.0.1` has been released to resolve this problem, thanks @askoufis

**Comment by raphaelboukara** [comment]
Issue resolved. thanks @askoufis
