### ISSUE TITLE
change name for good search result in google

### ISSUE THREAD

**Issue by yoonjong-park** [vanilla-extract-css/vanilla-extract#1284]
### Describe the bug

![스크린샷 2024-01-24 오후 1 57 07](https://github.com/vanilla-extract-css/vanilla-extract/assets/68855211/4a5fd2ef-933f-491b-bedd-d8189fcea83f)

It's too hard to everyone to find good result. 

### Reproduction

none

### System Info

```shell
none
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by airtonix** [comment]
You can get around this by just addin `js` to any search term.

`/vote wontfix`

**Comment by askoufis** [comment]
> You can get around this by just addin `js` to any search term.
> 
> `/vote wontfix`

Adding `css` also works well.

I agree that this is not something we're going to change in the foreseeable future, if ever.
