### ISSUE TITLE
Vite plugin shows a RerenceError when running test with vitest

### ISSUE THREAD

**Issue by lfantone** [vanilla-extract-css/vanilla-extract#1298]
### Describe the bug

After upgrading to the latest `@vanilla-extract/vite-plugin@4.0.0` all our test started failing with `__vanilla_globalCssAdapter__ is not defined`.

The test are running under `vitest`. Downgrading to a lower version the tests are working fine.

In the other hand, building with `vite` works fine (or at least doesn't throw any error in the output)

### Reproduction

https://codesandbox.io/p/devbox/586t6n

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.37 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    Yarn: 4.0.2 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.83
    Safari: 17.2.1
  npmPackages:
    @vanilla-extract/css: ^1.14.1 => 1.14.1
    @vanilla-extract/recipes: ^0.5.1 => 0.5.1
    @vanilla-extract/vite-plugin: ^4.0.0 => 4.0.0
    vite: ^5.0.12 => 5.0.12
```

### Used Package Manager

yarn

### Logs

```shell
FAIL  |adg-components| src/atoms/tag/tag.test.jsx [ src/atoms/tag/tag.test.jsx ]
ReferenceError: __vanilla_globalCssAdapter__ is not defined
 ❯ src/theme/theme.css.ts:3:20
      1| import { createTheme, createThemeContract } from '@vanilla-extract/css';
      2| 
      3| import { tokens as darkColors } from './dark-colors.js';
       |                    ^
      4| import { tokens as lightColors } from './light-colors.js';
      5| import { toThemeContract } from './utils.js';
 ❯ src/atoms/tag/tag.css.ts:4:31
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mrm007** [comment]
Thanks for reporting. This should be fixed in #1300.

Check out this CodeSandbox: https://codesandbox.io/p/github/mrm007/vanilla-extract-vite-plugin-v4-vitest/main
