### ISSUE TITLE
Build broken after vite-plugin 4.0.0

### ISSUE THREAD

**Issue by himself65** [vanilla-extract-css/vanilla-extract#1315]
### Describe the bug

```tsx
import classNames from 'classnames';
// @ts-expect-error no types
import styles from './App.module.css';
import './App.css';
import { container } from './styles.css.js'; // <-- import css.ts file
import { Counter } from './Counter.js';
import { Banner } from './Banner.js';

const App = ({ name }: { name: string }) => {
  return (
    <div style={{ border: '3px red dashed', margin: '1em', padding: '1em' }}>
      <title>Waku</title>
      <h1 className={classNames('foo', 'bar')}>Hello {name}!!</h1>
      <h1 className={styles.title}>Hello {name}!!</h1>
      <h3 className={container}>This is a server component.</h3>
      <Counter />
      <Banner />
    </div>
  );
};

export default App;
```

```shell
Error: Failed to load url /Users/himself65/Code/waku/examples/12_css/src/components/styles.css.ts.vanilla.css (resolved id: /Users/himself65/Code/waku/examples/12_css/src/components/styles.css.ts.vanilla.css). Does the file exist?
```

#### Way 1

```shell
git clone https://github.com/dai-shi/waku.git
pnpm run compile
cd examples/12_css
# upgrade plugin version
pnpm run dev
```

#### Way 2

https://stackblitz.com/edit/vitejs-vite-zjeowx?file=src%2FApp.tsx

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 11.30 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/75749_1707243849656/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/75749_1707243849656/bin/npm
    pnpm: 8.15.0 - ~/Library/Caches/fnm_multishells/75749_1707243849656/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    rollup: ^4.9.6 => 4.9.6 
    vite: 5.0.12 => 5.0.12
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by himself65** [comment]
Upstream: https://github.com/dai-shi/waku/issues/455

**Comment by himself65** [comment]
1. I cannot name my css file to `style.css.ts`
2. when add the file extension `.js`, it broken

**Comment by himself65** [comment]
For 2, why I have to add `.js` because moduleResolution is node16

**Comment by askoufis** [comment]
Taking a look at your reproduction, you only have an `App.css` file, not an `App.css.js` file. Updating the import to be `App.css` in `App.tsx` makes it work. The error had nothing to do with `style.css.ts`, that works fine.

**Comment by askoufis** [comment]
I haven't dived too deep into the `waku/examples/12_css` reproduction, but my hunch is that waku's dev server, which is a layer on top of `vite` (correct me if I'm wrong) is to blame. Potentially a change in https://github.com/dai-shi/waku/pull/240 could be the culprit?

**Comment by himself65** [comment]
> Taking a look at your stackblitz reproduction, you only have an `App.css` file, not an `App.css.js` file. Updating the import to be `App.css` in `App.tsx` makes it work. The error had nothing to do with `style.css.ts`, that works fine.

Oh I mistyped something, indeed this is not a issue

**Comment by himself65** [comment]
Maybe because some behavior in waku, I will check later

**Comment by himself65** [comment]
See https://github.com/vanilla-extract-css/vanilla-extract/pull/1353
