### ISSUE TITLE
Didn't get a result from child compiler error occurs when dynamic routes params like /blogs/[blog-id]

### ISSUE THREAD

**Issue by Katsukiniwa** [vanilla-extract-css/vanilla-extract#1322]
### Describe the bug

After upgrade @vanilla-extract/next-plugin from 2.3.5 to v2.3.6, `Didn't get a result from child compiler` error occurs when dynamic routes params like **_/blogs/[blog-id]_**, but **_/blogs/[id]_** don't occur error.

This is minimum reproduce repository
https://github.com/Katsukiniwa/nextjs-vanilla-extract-css-playground

reproduce step is
1. clone the above repository
2. run `npm install`
3. run `npm run dev`
4. access to `http://localhost:3000/blogs/1`
<img width="1542" alt="image" src="https://github.com/vanilla-extract-css/vanilla-extract/assets/35918681/ecd1c6be-ec7c-48d0-8314-4b5fd6f2f308">

### Reproduction

https://github.com/Katsukiniwa/nextjs-vanilla-extract-css-playground/actions/runs/7880973075/job/21503841452

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 327.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    npm: 10.2.5 - ~/.volta/tools/image/npm/10.2.5/bin/npm
    pnpm: 8.14.3 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.3.1
  npmPackages:
    @vanilla-extract/css: ^1.14.1 => 1.14.1 
    @vanilla-extract/next-plugin: ^2.3.6 => 2.3.6
```

### Used Package Manager

npm

### Logs

```shell
➜ npn run dev

> nextjs-vanilla-extract-css-playground@0.1.0 dev
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

 ✓ Ready in 2.7s
 ○ Compiling /blogs/[blog-id] ...
 ⨯ ./src/app/blogs/[blog-id]/page.css.ts
Error: Didn't get a result from child compiler
Import trace for requested module:
./src/app/blogs/[blog-id]/page.css.ts
 ⨯ ./src/app/blogs/[blog-id]/page.css.ts
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mrm007** [comment]
Hi @Katsukiniwa, thanks for reporting this.

It sounds like it's related to the latest fix we did for the Webpack plugin in https://github.com/vanilla-extract-css/vanilla-extract/pull/1247.

**Comment by Katsukiniwa** [comment]
@mrm007 
Thanks!
However, I do not understand the modified PR that you taught me due to my lack of technical skills, and it appears difficult to resolve this issue on my own.
Is it possible for one of the maintainers to handle this issue?

**Comment by mrm007** [comment]
@Katsukiniwa sorry, I didn't mean to say the solution is in the linked PR. Just a note to self and for @askoufis, who recently worked on that part of the codebase.
