### ISSUE TITLE
Windows css resolution

### ISSUE THREAD

**Issue by Nvos** [vanilla-extract-css/vanilla-extract#1344]
### Describe the bug

It seems that vite plugin function `getAbsoluteId` always receives unix path (even on windows) and uses `path.sep` due to which comparison fails on windows resulting in failing to find matching css in `cssCache`

Issue seems to be there:
https://github.com/vanilla-extract-css/vanilla-extract/blob/cff97a7f44014a5da33e8c56b2980b991ec49dd3/packages/vite-plugin/src/index.ts#L51

### Reproduction

https://github.com/Nvos/vanilla-extract-vinxi-repro

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 21.50 GB / 31.80 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    @vanilla-extract/css: ^1.14.1 => 1.14.1
    @vanilla-extract/vite-plugin: ^4.0.4 => 4.0.4
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
This could potentially be the same issue as #1339.

**Comment by himself65** [comment]
Same error here https://github.com/dai-shi/waku/pull/559
