### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by TheKnarf** [vanilla-extract-css/vanilla-extract#1350]
### Describe the bug

![Screenshot 2024-03-06 at 13 42 29](https://github.com/vanilla-extract-css/vanilla-extract/assets/213777/a4f44614-c1c2-4ca4-8769-ca3e1c6ea1e4)

The `function serialization API.` link is broken.

### Reproduction

- Go to https://vanilla-extract.style/documentation/packages/recipes/

- Click the `function serialization API.` link

### System Info

N/A

### Used Package Manager

N/A

### Logs

```shell
N/A
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
Strange, I would've though this was fixed in #1340. I'll take another look.

**Comment by askoufis** [comment]
@TheKnarf Thanks for raising the PR. This should be fixed in #1352, but only after a package release (our site publish is tied to package releases).
