### ISSUE TITLE
Error 'No CSS for file' with vite watch mode

### ISSUE THREAD

**Issue by JohnnyCrazy** [vanilla-extract-css/vanilla-extract#1372]
### Describe the bug

Similar to #1302, an error pops up when using the library mode of vite in combination with the `--watch` parameter. While the initial build succeeds, all incremental ones give an `No CSS for file` error.

No packages, which modify the tsconfig paths are installed. Pretty barebone setup, just vite + vanilla-extract. 

Let me know if you need more info!

### Reproduction

https://codesandbox.io/p/devbox/vanilla-bug-hc2k2l

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1
    Memory: 92.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.asdf/installs/nodejs/20.9.0/bin/node
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 118.0.5993.96
    Safari: 17.1
  npmPackages:
    @vanilla-extract/css: ^1.14.1 => 1.14.1
    @vanilla-extract/vite-plugin: ^4.0.6 => 4.0.6
    vite: ^5.2.0 => 5.2.6
```

### Used Package Manager

pnpm

### Logs

```shell
❯ pnpm build --watch

> vanilla-bug@0.0.0 build /Users/johnny/projects/vanilla-bug
> tsc && vite build "--watch"

vite v5.2.6 building for production...

watching for file changes...

build started...
✓ 17 modules transformed.
dist/style.css   0.02 kB │ gzip:  0.04 kB
dist/index.js   77.38 kB │ gzip: 19.34 kB
built in 260ms.

build started...
✓ 0 modules transformed.
[commonjs] Could not load /Users/johnny/projects/vanilla-bug/src/styles.css.ts.vanilla.css: No CSS for file: /Users/johnny/projects/vanilla-bug/src/styles.css.ts

build started...
✓ 0 modules transformed.
[commonjs] Could not load /Users/johnny/projects/vanilla-bug/src/styles.css.ts.vanilla.css: No CSS for file: /Users/johnny/projects/vanilla-bug/src/styles.css.ts
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JohnnyCrazy** [comment]
Seems to be similar to #1351 , but errors instead of not updating the styles.

**Comment by szszoke** [comment]
I just encountered this issue after trying this library out in an existing project.

**Comment by szszoke** [comment]
@askoufis I replied on the wrong issue. This is the issue that is still not fixed with 4.0.8.

**Comment by szszoke** [comment]
I made a tiny project where the issue can still be reproduced: https://github.com/szszoke/vanilla-vite-watch

I also added a patch with my if check that seems to resolve the issue. It can be applied via `npx patch-package` and reverted via `npx patch-package --reverse`.

**Comment by askoufis** [comment]
> I made a tiny project where the issue can still be reproduced: https://github.com/szszoke/vanilla-vite-watch
> 
> I also added a patch with my if check that seems to resolve the issue. It can be applied via `npx patch-package` and reverted via `npx patch-package --reverse`.

Oops. I was so focused on the `buildEnd` and `closeWatcher` hooks that I forgot to add that if statement 🤦. I can't actually reproduce the error in your repo, but I still think your patch makes sense to do. I've released this change in [`@vanilla-extract/vite-plugin@4.0.9](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%404.0.9)`.

**Comment by szszoke** [comment]
Thanks for the quick reaction!

I tried it on Linux and Node 20. If you tested on a different platform then my hunch is that the file watching logic has a slightly different behavior.

@JohnnyCrazy, could you test whether you still have the issue?

**Comment by JohnnyCrazy** [comment]
It seems fixed on the latest version, styles are correctly updated and written, thanks 👍🏼
