### ISSUE TITLE
Doesn't work since v4

### ISSUE THREAD

**Issue by grybykm** [vanilla-extract-css/vanilla-extract#1396]
### Describe the bug

I'm getting an error after upgrading @vanilla-extract/vite-plugin from 3.9.5 to v4 (4.0.7)
`vite: 5.2.10`

```
error during build:
Error: [vanilla-extract] Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/getting-started
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.

**Comment by askoufis** [comment]
Your issue is impossible to diagnose without some kind of minimal reproduction. It would be much appreciated if you could provide one via a github repo/stackblitz/etc.

**Comment by grybykm** [comment]
After removing `vite-plugin-css-modules` completely the issue was fixed!
