### ISSUE TITLE
error TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by itsanishjain** [vanilla-extract-css/vanilla-extract#1416]
### Describe the bug

Getting error 

`yarn add @vanilla-extract/next-plugin`

![image](https://github.com/vanilla-extract-css/vanilla-extract/assets/43033153/85902331-e355-4bc7-8cfa-9aa6aa4ed08a)

I am using Nextjs 14

how to fix this 

### Reproduction

no link

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700HX
    Memory: 3.13 GB / 15.75 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
This is not an issue related to Vanilla Extract, but likely your node version. See https://github.com/nodejs/node/issues/48855 (try upgrading to the latest version of node 18, or even node 20).
