### ISSUE TITLE
can we disable `url()` resolving in vanilla-extract-webpack plugin ?

### ISSUE THREAD

**Issue by taozhou-glean** [vanilla-extract-css/vanilla-extract#1456]
### Describe the bug

```
Can't resolve '/images/some-image.svg' in 'node_modules/.pnpm/@vanilla-extract+webpack-plugin@2.3.11_@types+node@20.14.13_babel-plugin-macros@3.1.0_less@4.2.0_webpack@5.93.0/node_modules/@vanilla-extract/webpack-plugin'
```

### Reproduction

we serve all our image assets in a public CDN, so the path set in the `url` is not the relative path to resolve the image file locally, and we don't want them to be resolved, but instead, just use the raw value, so would be nice if we have the option just like css-loader to disable the url resolving

### System Info

```shell
command not working
macos - vanilla-extract webpack plugin 2.3.11
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by taozhou-glean** [comment]
we already have `url:false` BTW

```
 {
      test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: require.resolve('css-loader'),
          options: {
            url: false, // Required as image imports should be handled via JS/TS import statements
          },
        },
      ],
    },
```

**Comment by taozhou-glean** [comment]
error looks very similar to https://github.com/vanilla-extract-css/vanilla-extract/issues/462, but on webpack-plugin (not entirely sure what it uses underneath for compiling, I assume its babel by default ?, we use SWC for ts compiling)

**Comment by taozhou-glean** [comment]
hmm i think I know why now, so we want to use raw value in `url()`, is it possible to disable url resolving within vanilla webpack plugin ?

**Comment by askoufis** [comment]
Vanilla Extract doesn't perform any URL resolution. That's entire up to your bundler configuration. In a test repo, I've set `url: false` on `css-loader`, and the following style works as expected:

```tsx
export const urlTest = style({
  backgroundImage:
    'url(https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=800)',
  width: '800px',
  height: '800px',
});
```

If you could provide a minimal reproduction, that would help narrow down the issue.

**Comment by taozhou-glean** [comment]
oh i wonder if its because we are using relative path and it tries to resolve that compared to full absolute path 🤔

**Comment by askoufis** [comment]
@taozhou-glean Is there any update on this? I'm not sure this is relevant to Vanilla Extract because, as mentioned previously, it doesn't handle `url` resolution, that's delegated to the bundler.

**Comment by taozhou-glean** [comment]
Right, my bad, it's actually a different issue, we can close this one
