### ISSUE TITLE
Missing pseudo-class: -webkit-calendar-picker-indicator

### ISSUE THREAD

**Issue by corradopetrelli** [vanilla-extract-css/vanilla-extract#1474]
### Describe the bug

WebkitCalendarPickerIndicator is not available on vanilla-extract

### Reproduction

It is missing from simplePseudo file https://github.com/vanilla-extract-css/vanilla-extract/blob/1e48d966c2add14a92febe11fa0a1b66b5a45740/packages/css/src/simplePseudos.ts on codebase

### System Info

```shell
System:
    OS: macOS 14.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.78 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.14.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@corradopetrelli This has been released in https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.16.0.
