### ISSUE TITLE
[VITE] - vite-plugin of vanilla-extract is not updating CSS style after saving.

### ISSUE THREAD

**Issue by Darter90** [vanilla-extract-css/vanilla-extract#1481]
### Describe the bug

After initializing a new testing installation of Vite + React, and after following the basic guidelines for installing vanilla-extract, it seems that the vite-plugin is not updating the CSS when saving a new change in watch mode:

![Screenshot 2024-09-30 211754](https://github.com/user-attachments/assets/b0e8bf66-a2b2-4470-a499-f499a1144062)

By swapping vite-plugin version on the package.json, I found that the issue is happening only when using "@vanilla-extract/vite-plugin": "4.0.13 - 14 -15"; while using "@vanilla-extract/vite-plugin": "4.0.12", the issue disappear and the plugin is working as intended.

### Reproduction

https://github.com/Darter90/react-vite-typescript-vanillaextract

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 18.53 GB / 31.71 GB
  Binaries:
    Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.52)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vanilla-extract/css: ^1.15.5 => 1.15.5
    @vanilla-extract/sprinkles: ^1.6.3 => 1.6.3
    @vanilla-extract/vite-plugin: 4.0.15 => 4.0.12
    vite: ^5.4.1 => 5.4.8
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
Looks like [this change in v4.0.13](https://github.com/vanilla-extract-css/vanilla-extract/pull/1438/files#diff-610bb6af1585f8ecc202e248277bf1857d8a2eef08cdd1dc81cfd0428bec85c7R217) broke HMR invalidation for files that don't end in `.css.ts`. I'd suggest renaming the file to `.css.ts`, unless you absolute have to export JSX alongside your VE styles (I don't even know if that would work?).

This will be fixed by https://github.com/vanilla-extract-css/vanilla-extract/pull/1482.

**Comment by askoufis** [comment]
@Darter90 This fix was released in https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fvite-plugin%404.0.16

**Comment by Darter90** [comment]
Thank you very much; I tested on my own and it compiles now.
