### ISSUE TITLE
Error: Cannot find module '@vanilla-extract/css/adapter

### ISSUE THREAD

**Issue by KwangminNam** [vanilla-extract-css/vanilla-extract#1502]
### Describe the bug

env:nextjs 15
react:18
yarn monorepo workspace

I'm getting this error while i ran the nextjs client server

### Reproduction

Error

### System Info

```shell
Chrome / Mac )S
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
@KwangminNam Please provide a minimal reproduction of your issue. It's very hard to diagnose an issue without any code to run/look at.
