### ISSUE TITLE
CssProperties type error in 'assignInlineVars' in React (Vite + Pnpm)

### ISSUE THREAD

**Issue by klmhyeonwoo** [vanilla-extract-css/vanilla-extract#1504]
### Describe the bug

<img width="677" alt="스크린샷 2024-11-16 오후 8 53 01" src="https://github.com/user-attachments/assets/9a8166ee-a940-405e-92aa-06f5636ac870">

I am attaching a photo regarding this.

### Reproduction

https://github.com/klmhyeonwoo/vanila-extract-test

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 59.70 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 8.15.5 - /opt/homebrew/bin/pnpm
    Watchman: 2024.08.26.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.119
    Safari: 17.1
    Safari Technology Preview: 18.0
  npmPackages:
    @vanilla-extract/css: ^1.16.0 => 1.16.0 
    @vanilla-extract/dynamic: ^2.1.2 => 2.1.2 
    @vanilla-extract/vite-plugin: ^4.0.17 => 4.0.17 
    vite: ^5.4.10 => 5.4.11
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
I can't seem to reproduce the type error in your screenshot. Your usage of `assignInlineVars` looks correct to me. I ran `tsc --noEmit` and (other than unused imports) didn't see any errors.

**Comment by klmhyeonwoo** [comment]
Um... That's right, no error occurs during build.

I am using 'webstorm'. A red line appears in 'webstorm', but there seems to be no problem while using it.

I think it may be a problem with IDE type inference.

**Comment by askoufis** [comment]
Could you try turning off and on `Show project errors` in your settings? See https://stackoverflow.com/a/76193154.

**Comment by klmhyeonwoo** [comment]
The problem still occurs...
I need to look further to see if there are any related issues.

**Comment by klmhyeonwoo** [comment]
To. @askoufis 
This issue seems to only occur in certain IDEs and environments.
We have determined that the issue is not related to the `lib so we will close the issue.
