### ISSUE TITLE
Unable to configure app for testing

### ISSUE THREAD

**Issue by carlosnufe** [vanilla-extract-css/vanilla-extract#435]
Hi,

I have a project with React + TypeScript + Webpack raw configuration where everything was working fine, until I wanted to test a component that was using styles.

I get 

```bash
 Test suite failed to run

    Styles were unable to be assigned to a file. This is generally caused by one of the following:

    - You may have created styles outside of a '.css.ts' context
    - You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup

      1 | import { createGlobalTheme, globalStyle, globalFontFace } from '@vanilla-extract/css';
      2 |
    > 3 | globalFontFace('Roboto', {
        |               ^
      4 |   src: "url('src/assets/fonts/Roboto/Roboto-Regular.ttf') format('truetype')",
      5 | });
      6 |
``` 

I have a `.css.ts` for a recipe that consumes the `global.css.ts` theme and the component that imports the first.

So

```javascript
import { style } from './style.css.ts'

<Component className={style(variant1: value, variant2: value)} />
```

I checked the doc, there's only a mention of a babel plugin, I'm not using babel only TS.

For testing, I'm using Jest, with the following configuration

```javascript
testEnvironment: 'jsdom',
preset: 'ts-jest'
```

Could you help me?

**Comment by dagda1** [comment]
> After some reading, I found the solution.
> 
> As said, I'm using `ts-jest` and it may be configured through the `globals` property on the jest configuration, check out the [doc](https://kulshekhar.github.io/ts-jest/docs/getting-started/options).
> 
> So, given the plugin `@vanilla-extract/babel-plugin`, the configuration is as follows
> 
> ```js
> // jest.config.{js|ts} or package.json
> (...)
> globals: {
>   babelConfig: {
>     plugins: ["@vanilla-extract/babel-plugin"]
>   }
> },
> (...)
> ```

THank you for adding this comment but you forgot to add the enclosing `ts-jest` property that wraps `babelConifg`.

It should be:

```ts
globals: {
  'ts-jest': {
    babelConfig: {
      plugins: ['@vanilla-extract/babel-plugin'],
    },
  },
},
```

It took me a while to realise this,  Could you please update the comment for anyone else?

**Comment by carlosnufe** [comment]
Hi @dagda1, I've updated the comment.
I wrote it that way because `babelConfig` is not the unique attribute. I linked the doc for that matter.
