### ISSUE TITLE
Proposal: allow undefined values in sprinkles function 

### ISSUE THREAD

**Issue by disintegrator** [vanilla-extract-css/vanilla-extract#452]
Hey folks, this is a proposal for a quality of life improvement that permits passing possible undefined prop values to the sprinkles function.

Given this props interface for a component:

```ts
export interface TypeProps {
  fontFamily?: FontFamily;
  color?: Sprinkles["color"];
  display?: Sprinkles["display"];
  textSize?: Sprinkles["textSize"];

  margin?: Sprinkles["margin"];
  marginInline?: Sprinkles["marginInline"];
  marginInlineStart?: Sprinkles["marginInlineStart"];
  marginInlineEnd?: Sprinkles["marginInlineEnd"];
  marginBlock?: Sprinkles["marginBlock"];
  marginBlockStart?: Sprinkles["marginBlockStart"];
  marginBlockEnd?: Sprinkles["marginBlockEnd"];
}
```

I'm currently having to do this:

```ts
export function useTextStyle(props: TypeProps) {
  const {
    fontFamily,
    color,
    display,
    textSize,
    margin,
    marginInline,
    marginInlineStart,
    marginInlineEnd,
    marginBlock,
    marginBlockStart,
    marginBlockEnd,
  } = props;

  return classNames(
    sprinkles({ margin: "u0" }),
    fontFamily ? fontFamilies[fontFamily] : null,
    sprinkles({
      ...(color ? { color } : null),
      ...(display ? { display } : null),
      ...(textSize ? { textSize } : null),

      ...(margin ? { margin } : null),
      ...(marginInline ? { marginInline } : null),
      ...(marginInlineStart ? { marginInlineStart } : null),
      ...(marginInlineEnd ? { marginInlineEnd } : null),
      ...(marginBlock ? { marginBlock } : null),
      ...(marginBlockStart ? { marginBlockStart } : null),
      ...(marginBlockEnd ? { marginBlockEnd } : null),
    })
  );
}
```

I'd love to be able to do this instead:

```ts
export function useTextStyle(props: TypeProps) {
  const { fontFamily, ...sprinklers } = props;

  return classNames(
    sprinkles({ margin: "u0" }),
    fontFamily ? fontFamilies[fontFamily] : null,
    sprinkles(sprinklers)
  );
}
```

But i get a bunch of compile errors like this one:

```
Type '{ light?: Color; dark?: Color; } | undefined' is not assignable to type '{ light?: Color; dark?: Color; }'.
  Type 'undefined' is not assignable to type '{ light?: Color; dark?: Color; }'.ts(2322)
```

**Comment by mattcompiles** [comment]
I think this makes sense, not sure how difficult it would be to add though as the Sprinkles types are quite complex. Would be happy to accept a PR. 😄

**Comment by askoufis** [comment]
@disintegrator I'm having trouble reproducing this error.
The code below has no type errors.
```ts
const colors = {
  'blue-50': '#eff6ff',
  'blue-100': '#dbeafe',
  'blue-200': '#bfdbfe',
  'gray-700': '#374151',
  'gray-800': '#1f2937',
  'gray-900': '#111827',
};

const colorProperties = defineProperties({
  conditions: {
    lightMode: {},
    darkMode: { '@media': '(prefers-color-scheme: dark)' },
  },
  defaultCondition: 'lightMode',
  properties: {
    color: colors,
    background: colors,
  },
});

const responsiveProperties = defineProperties({
  defaultCondition: 'mobile',
  conditions: {
    mobile: {},
    tablet: { '@media': 'screen and (min-width: 768px)' },
    desktop: { '@media': 'screen and (min-width: 1024px)' },
  },
  responsiveArray: ['mobile', 'tablet', 'desktop'],
  properties: {
    display: ['flex', 'none', 'block'],
  },
});

const sprinkles = createSprinkles(colorProperties, responsiveProperties);

type Sprinkles = Parameters<typeof sprinkles>[0];

type Props = {
  display?: Sprinkles['display'];
  color?: Sprinkles['color'];
};

const useTextStyle = (props: Props) => {
  return sprinkles(props);
};
```

**Comment by askoufis** [comment]
@disintegrator Maybe it's something to do with your specific setup. When I copied the code from your sandbox into my local repo, I don't get the error, I can even see `| undefined` on the property type.

I even tried forking an existing VE sandbox and copying your code there, and I was still unable to reproduce the error.
[Sandbox](https://codesandbox.io/p/sandbox/reverent-lederberg-tqlzly?file=%2Fsrc%2Fsprinkles.css.ts&selection=%5B%7B%22endColumn%22%3A6%2C%22endLineNumber%22%3A60%2C%22startColumn%22%3A6%2C%22startLineNumber%22%3A60%7D%5D)

**Comment by askoufis** [comment]
Oh nvm, it was `@tsconfig/strictest`. Removing `"extends": "@tsconfig/strictest/tsconfig.json"` from tsconfig that makes the error go away, though I'd be keen to know which tsconfig setting in particular is the culprit.

**Comment by askoufis** [comment]
Ah, it's [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes).

**Comment by disintegrator** [comment]
@askoufis I should've mentioned that. My bad! I always run with the strictest TS settings possible.

**Comment by askoufis** [comment]
@disintegrator

**Comment by disintegrator** [comment]
> @disintegrator #1034

Niiiiiiice! 🙌

**Comment by askoufis** [comment]
Feel free to test the change out if you want with this snapshot version of sprinkles: `@vanilla-extract/integration@0.0.0-sprinkles-type-explicit-undefined-202329123141`

**Comment by disintegrator** [comment]
@askoufis just updated my sandbox with that candidate release and it appears to be working as expected. Thanks again!
