### ISSUE TITLE
assignInlineVars doesnt accept undefined values

### ISSUE THREAD

**Issue by sami616** [vanilla-extract-css/vanilla-extract#536]
Looks like right now we can work around this by passing an empty string, like so:

```
 style={assignInlineVars({ [pointColor]: point.color ?? '' })}
```

However, a nice quality of life change would be  to just pass a possibly undefined value and let a `fallbackVar` handle it in my .css.ts

**Comment by pladaria** [comment]
Additionally, passing an empty string produces hydration issues with SSR

**Comment by askoufis** [comment]
I've commented on #1175 about this too, but what should the behaviour be when you pass `undefined`? Should it `unset` the variable, or omit it from the style object altogether? Should `null` be handled the same way?
