### ISSUE TITLE
babel plugin add packageIdentifiers config

### ISSUE THREAD

**Issue by kingback** [vanilla-extract-css/vanilla-extract#603]
https://github.com/seek-oss/vanilla-extract/blob/b221532b1e4f5be146a45403ece0e29ebcdf2cf3/packages/babel-plugin/src/index.ts#L236

I'm trying to import `style/globalStyle` from my custom package, it works in webpack plugin, but babel plugin won't work because it defines `packageIdentifiers` locally in plugin code.

```js
// my-app
export { style, globalStyle } from '@vanilla-extract/css';

// index.css.ts
import { style, globalStyle } from 'my-app';

// babel.config.js
{
  plugins: [
    ['@vanilla-extract/babel-plugin', {
      packageIdentifiers: ['my-app']
    }]
  ]
}
```

**Comment by askoufis** [comment]
Closing as the issue should no longer relevant now that [the babel plugin has been deprecated](https://www.npmjs.com/package/@vanilla-extract/babel-plugin).
