### ISSUE TITLE
Type Error with example from documentation

### ISSUE THREAD

**Issue by deecewan** [vanilla-extract-css/vanilla-extract#686]
### Describe the bug

When following the documentation for [createGlobalTheme](https://vanilla-extract.style/documentation/styling-api/#createglobaltheme) with theme contracts, there is a type error:

```
Type '"blue"' is not assignable to type 'MapLeafNodes<CSSVarFunction | MapLeafNodes<any, CSSVarFunction>, string>'.ts(2322)

App.css.ts(5, 5): The expected type comes from property 'brand' which is declared here on type 'MapLeafNodes<MapLeafNodes<{ brand: any; }, CSSVarFunction>, string>'
```

The code is copied directly from the documentation.

This seems like a duplicate of #483 and #484, which were apparently fixed by #489, but I'm still seeing this issue both locally and in the code sandbox.

### Link to reproduction

https://codesandbox.io/s/proud-glade-rvv2h6?file=/src/App.css.ts

### System Info

(taken from the above CodeSandbox)

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 2.42 GB / 62.72 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    @vanilla-extract/css: 1.7.0 => 1.7.0
    @vanilla-extract/sprinkles: ^1.3.3 => 1.3.3
    @vanilla-extract/webpack-plugin: ^2.1.8 => 2.1.8
    webpack: ^5.36.1 => 5.36.1

```

**Comment by tojump** [comment]
Getting this too.

**Comment by mattcompiles** [comment]
Hey :wave,

I believe this is a TypeScript quirk around `strict` mode, or more specifically `strictNullChecks`. For the `null` values in global theme to work you must have `strictNullChecks` enabled in your `tsconfig`. Alternatively using string values e.g. `blue: ''` will work. However, I'd suggest all projects should really be running `strict: true` if possible.

**Comment by askoufis** [comment]
I forked [the reproduction sandbox](https://codesandbox.io/s/proud-glade-rvv2h6?file=/src/App.css.ts) and updated all Vanilla Extract packages to their latest versions and there are no errors.

[Updated sandbox](https://codesandbox.io/p/sandbox/interesting-meitner-ebf0c3?welcome=true).
