### ISSUE TITLE
@vanilla-extract/vite-plugin CSS included in ESM & UMD bundle when using Vite in library mode

### ISSUE THREAD

**Issue by dalhaan** [vanilla-extract-css/vanilla-extract#745]
### Describe the bug

The raw compiled CSS is included in ESM and UMD bundles (but not CJS) when building a library with Vite. This could result in large bundle sizes as the CSS grows.

The CSS is included in the bundle as variables, but the variables themselves are never referenced in the code.

```js
// es
var ExampleComponent_css_ts_vanilla = /* @__PURE__ */ (() => "._1rs50ag0{width:300px;height:100px;display:flex;align-items:center;justify-content:center;color:#fff;background-color:#222;border:2px solid gray;border-radius:10px}\n")();

// umd
var g=(()=>`._1rs50ag0{width:300px;height:100px;display:flex;align-items:center;justify-content:center;color:#fff;background-color:#222;border:2px solid gray;border-radius:10px}`)()
```

This isn't a huge issue if the library is being consumed as a node module in another app as the variables should be excluded from the final bundles as they are not referenced anywhere but this could be problematic if the bundle is being served from a CDN and consumed using a script tag due to the extra redundant bytes.

e.g.

```html
<script type="module" src="https://<CDN_DOMAIN>/<VERSION>/es/bundle.min.js"></script>
```

I haven't tested whether or not this happens when not using Vite in library mode.

In the StackBlitz reproduction below, the problem can be found in:

- `dist/index.es.js` @ line 2
- `dist/index.umd.js` @ line 1

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9774qe

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 77.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 103.1.40.113
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
    Safari: 15.4
    Safari Technology Preview: 16.0
  npmPackages:
    @vanilla-extract/babel-plugin: ^1.1.7 => 1.1.7 
    @vanilla-extract/css: ^1.7.2 => 1.7.2 
    @vanilla-extract/vite-plugin: ^3.2.1 => 3.2.1 
    vite: ^2.9.9 => 2.9.12
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment]
This no longer seems to be the case with the latest versions of `vite` (4.5.0) and `@vanilla-extract/vite-plugin` (v3.9.0). A separate `style.css` file is generated, and the javascript only contain references to the classname and no longer embed the CSS.

Going to close this issue, but feel free to re-open it if that was a mistake.
