### ISSUE TITLE
Vite Plugin Peer Dependency Prevents Vite 3.0

### ISSUE THREAD

**Issue by mcclayton** [vanilla-extract-css/vanilla-extract#760]
### Describe the bug

Now that [Vite 3 is out](https://vitejs.dev/blog/announcing-vite3.html), there don't appear to be any changes preventing Vanilla Extract from supporting `"vite": "^2.2.3 || ^3.0.0-0"` as a peer dependency.

Without updating the peer dependency in this repo, and attempting to install the Vite 3 gives:
```
npm ERR! Found: vite@3.0.2
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.2.3" from @vanilla-extract/vite-plugin@3.2.1
npm ERR! node_modules/@vanilla-extract/vite-plugin
npm ERR!   dev @vanilla-extract/vite-plugin@"^3.2.1" from the root project
```

### Reproduction

Reproduction

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.33 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
```

### Used Package Manager

npm

### Logs

```shell
npm ERR! Found: vite@3.0.2
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.2.3" from @vanilla-extract/vite-plugin@3.2.1
npm ERR! node_modules/@vanilla-extract/vite-plugin
npm ERR!   dev @vanilla-extract/vite-plugin@"^3.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ztrehagem** [comment]
This is my workaround to prevent the peer dependency error:
```jsonc
  // package.json
  "overrides": {
    "@vanilla-extract/vite-plugin": {
      "vite": "^3"
    }
  },
```

**Comment by florianmatz** [comment]
Any updates on this? I've hoped that this would be added to the new release of the vite plugin. Forcing the install and using actual version does work as far as i can see; so there is no reason to keep the old peer dependency?

**Comment by tom-sherman** [comment]
It appears that there are no breaking changes in Vite 3, I've created a PR to add it to the peer dependencies.
