### ISSUE TITLE
SprinklesError when using vars object from theme in defineProperties

### ISSUE THREAD

**Issue by lotusjohn** [vanilla-extract-css/vanilla-extract#820]
### Describe the bug

I use createThemeContract() and createTheme to setup a theme.
I want to use the variables from the contract in the definedProperties in sprinkles. 

Theme looks like this (removed unrelated keys):
```
 //THEME.CSS.TS 
const tokens = createThemeContract({
  colors: {
    brand1: "",
    black: "",
    dark: "",
    white: "",
    blackAlpha: "",
    whiteAlpha: "",
  },

});

const themeA = createTheme(tokens, {
  colors: {
    brand1: '#F39C6B',
    black: '#121113',
    dark: '#444',
    white: '#FFFFFF',
    blackAlpha: '#121113aa',
    whiteAlpha: '#FFFFFFaa',
  }
});

_//SPRINKLES.CSS.TS_
const colorProperties = defineProperties({
  conditions: {
    lightMode: {},
    darkMode: { '@media': '(prefers-color-scheme: dark)' },
  },
  defaultCondition: 'lightMode',
  properties: {
   *background: tokens.colors,
    color: tokens.colors,
  },
});
```
It gives this error when trying to use a token in a component's sprinkles.

`NonErrorEmittedError: (Emitted value instead of an instance of Error) SprinklesError: "background" has no value "var(--colors-whiteAlpha__9aytcy5)". Possible values are "brand1", "black", "dark", "white", "blackAlpha", "whiteAlpha".`

But, if i do this is definedProperties() it does work:
```
//SPRINKLES.CSS.TS
const colorProperties = defineProperties({
  conditions: {
    lightMode: {},
    darkMode: { '@media': '(prefers-color-scheme: dark)' },
  },
  defaultCondition: 'lightMode',
  properties: {
    background: Object.values(tokens.colors),
    color: Object.values(tokens.colors),
  },
});
```

So im not sure why this happens, the docs says we should be able to just use it as the object it is.
```
//https://vanilla-extract.style/documentation/packages/sprinkles/
import { defineProperties } from '@vanilla-extract/sprinkles';
import { vars } from './vars.css.ts';

const responsiveProperties = defineProperties({
  properties: {
    gap: vars.space
    // etc.
  }
});
```

In addition, i also have a ts error on the tokens (the variables from the themeContract):
`The inferred type of 'tokens' cannot be named without a reference to '.pnpm/@vanilla-extract+private@1.0.3/node_modules/@vanilla-extract/private'. This is likely not portable. A type annotation is necessary.ts(2742)`

### Reproduction

(will provide soon)

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 26.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Brave Browser: 103.1.41.96
    Chrome: 105.0.5195.102
    Safari: 14.0
```

### Used Package Manager

pnpm

### Logs

```shell
//runtime error log
NonErrorEmittedError: (Emitted value instead of an instance of Error) SprinklesError: "background" has no value "var(--colors-whiteAlpha__9aytcy5)". Possible values are "brand1", "black", "dark", "white", "blackAlpha", "whiteAlpha".

//ts error
The inferred type of 'tokens' cannot be named without a reference to '.pnpm/@vanilla-extract+private@1.0.3/node_modules/@vanilla-extract/private'. This is likely not portable. A type annotation is necessary.ts(2742)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bram209** [comment]
> In addition, i also have a ts error on the tokens (the variables from the themeContract):
The inferred type of 'tokens' cannot be named without a reference to '.pnpm/@vanilla-extract+private@1.0.3/node_modules/@vanilla-extract/private'. This is likely not portable. A type annotation is necessary.ts(2742)

I ran into the same issue, as a workaround you may type it explicitly:

```typescript
import { createTheme, createThemeContract } from "@vanilla-extract/css";
import { ThemeVars } from "@vanilla-extract/css/dist/declarations/src/types";

const tokens = {
  color: {
    brand: "",
  },
  font: {
    body: "",
  },
};

export const vars: ThemeVars<typeof tokens> = createThemeContract(tokens);

export const blueThemeClass = createTheme(vars, {
  color: {
    brand: "blue",
  },
  font: {
    body: "arial",
  },
});
```

**Comment by rothsandro** [comment]
How do you use the sprinkles? From the error it looks like you're passing a token to the sprinkles function `sprinkles({ background: tokens.colors.brand1 })` but you need to pass the key of your token as a string `sprinkles({ background: "brand1" })`. But a repro would be helpful.

**Comment by lotusjohn** [comment]
@bram209 That solved the issue!'
@rothsandro You're right, i did make that mistake! 😅 

Thanks a lot guys!

**Comment by margalit** [comment]
I had similar issues in a pnpm monorepo and was able to resolve it by adding and explicitly importing `@vanilla-extract/private` at the top of my theme.css.ts file eg:

```typescript
import '@vanilla-extract/private'
```
This hints to pnpm that the type import was intentional and should be included.

**Comment by askoufis** [comment]
I tested the following styles in an app with the latest versions of `@vanilla-extract/css` (1.13.0) and `@vanilla-extract/sprinkles` (1.6.1) and there were no errors:

```ts
import { createTheme, createThemeContract } from "@vanilla-extract/css";
import { defineProperties, createSprinkles } from "@vanilla-extract/sprinkles";

const tokens = createThemeContract({
  colors: {
    brand1: "",
    black: "",
    dark: "",
    white: "",
    blackAlpha: "",
    whiteAlpha: "",
  },
});

export const themeA = createTheme(tokens, {
  colors: {
    brand1: "#F39C6B",
    black: "#121113",
    dark: "#444",
    white: "#FFFFFF",
    blackAlpha: "#121113aa",
    whiteAlpha: "#FFFFFFaa",
  },
});

const colorProperties = defineProperties({
  conditions: {
    lightMode: {},
    darkMode: { "@media": "(prefers-color-scheme: dark)" },
  },
  defaultCondition: "lightMode",
  properties: {
    background: tokens.colors,
    color: tokens.colors,
  },
});

export const sprinkles = createSprinkles(colorProperties);
```

There should be no need to add a side-effect import for `@vanilla-extract/private`. Closing this issue.
