### ISSUE TITLE
CSS Media Queries are not ordered reliably

### ISSUE THREAD

**Issue by benweiser** [vanilla-extract-css/vanilla-extract#874]
### Describe the bug

This is another manifestation of the same issue addressed [here](https://github.com/vanilla-extract-css/vanilla-extract/issues/141). I have tried to no avail create a minimal reproduction of this issue, but can't seem to get it to work. In my project (like the previous issue author) I am able to reliably reproduce this.

After building my project the output CSS [looked like this](https://gist.github.com/benweiser/819695bde3a361bf856ca166ed212d9a) I have left comments to demonstrate where the specific problem is with the ordering.

I would expect media queries like this to be sorted from the smallest viewport width value to the largest.

Disabling the optimization by making `mergeIfCompatible` always return false and commenting out the merge in `transformCss` caused the styles to behave as expected.

Can we please have a configuration option to disable this optimization even if the bug is fixed? 

It feels like a bit more magic than I'd want the lib to be responsible for. I ended up using [this postcss plugin](https://www.npmjs.com/package/postcss-sort-media-queries) to get the expected output.

### Reproduction

https://codesandbox.io/s/naughty-newton-uhy6xr

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 117.04 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox Developer Edition: 105.0
    Safari: 16.0
  npmPackages:
    @vanilla-extract/babel-plugin: ^1.2.0 => 1.2.0 
    @vanilla-extract/css: https://gitpkg.now.sh/benweiser/vanilla-extract/packages/css?disable-automatic-mq-optimization => 1.9.1 
    @vanilla-extract/jest-transform: ^1.0.1 => 1.0.1 
    @vanilla-extract/next-plugin: ^2.1.1 => 2.1.1 
    @vanilla-extract/recipes: ^0.2.5 => 0.2.5 
    @vanilla-extract/webpack-plugin: ^2.1.12 => 2.2.0
```

### Used Package Manager

pnpm

### Logs

```shell
N/A
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by benweiser** [comment]
Here is a full reproduction I wasn't able to demonstrate in my previous sandbox.

https://codesandbox.io/s/naughty-newton-uhy6xr
![Screen Shot 2022-10-07 at 11 00 18 AM](https://user-images.githubusercontent.com/10409239/194621183-0aa456cc-bdb7-472b-9651-ed139ea77ea9.png)

Note the 768px min width media query comes later in the cascade than the 1024px media query.

**Comment by mihaisavezi** [comment]
Can confirm this still happens on `@vanilla-extract/css@1.9.1`

**Comment by mattcompiles** [comment]
I have just opened a PR to fix this issue. 

I understand the desire to turn this behaviour off, however it's not a simple option to add. Also, as you always nest media queries within styles in VE it means you'd end up with a large amount of condition duplication that is unavoidable if we removed it completely.
