### ISSUE TITLE
selectors using a recipe with variants generates incorrect css

### ISSUE THREAD

**Issue by PHILLIPS71** [vanilla-extract-css/vanilla-extract#944]
### Describe the bug

I'm in the process of converting an existing stitches based design system over to use vanilla-extract, but have ran into a issue on where I cannot reference child classes inside of a recipe variant. Instead it wants me to reference the parent inside the child after reading this error that I receive at build time.

> Style selectors must target the '&' character (along with any modifiers), e.g. `${parent} &` or `${parent} &:hover`.

> This is to ensure that each style block only affects the styling of a single class.

> If your selector is targeting another class, you should move it to the style definition for that class, e.g. given we have styles for 'parent' and 'child' elements, instead of adding a selector of `& ${child}`) to 'parent', you should add `${parent} &` to 'child').

So that's exactly what I've done in this case, the code below is the changes that I've made where that navbar recipe is the parent element.

```tsx
export const container = style({
  ...

  selectors: {
    [`${navbar({ kind: 'floating' })} &`]: {
      marginTop: vars.spaces[6],
      marginRight: vars.spaces[6],
      marginLeft: vars.spaces[6],
      borderRadius: vars.radii.md,
      borderBottom: 'none'
    },
  },
})
```

Although when the navbar has the kind floating variant applied the styles in the selector are not being set, after some digging I've realised that this is due to the styles are the getting generated seem to be incorrect. Below are the styles that have been generated:

```css
.Navbar_navbar__xhan6d0 .Navbar_navbar_kind_floating__xhan6d3 .Navbar_container__xhan6d4 {
    margin-top: var(--spaces-6__zxivqp3j);
    margin-right: var(--spaces-6__zxivqp3j);
    margin-left: var(--spaces-6__zxivqp3j);
    border-radius: var(--radii-md__zxivqp4d);
    border-bottom: none
}
```

Shouldn't the class names be defined as `.Navbar_navbar__xhan6d0.Navbar_navbar_kind_floating__xhan6d3 .Navbar_container__xhan6d4`, removing the space between the navbar variants classes as these are all class names that are appended into the navbar element?

### Reproduction

https://github.com/PHILLIPS71/vanilla-extract-issue

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 39.64 GB / 63.91 GB
  Binaries:
    Node: 16.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.99
    Edge: Spartan (44.22621.819.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vanilla-extract/css: ^1.9.2 => 1.9.2
    @vanilla-extract/esbuild-plugin: ^2.2.0 => 2.2.0
    @vanilla-extract/recipes: ^0.3.0 => 0.3.0
    @vanilla-extract/sprinkles: ^1.5.1 => 1.5.1
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mahendradambe** [comment]
The behavior of `runtimeFn(variantSelection)` seems correct as the resulting string is passed to `className` prop.
For now, you can try something like this if you want to use recipe
```ts
{
	[`${navbar({ kind: 'floating' }).join('')} &`]: { /* styles */ } 
}
```
This however has unnecessary classes in the selector e.g, 
`.Navbar_navbar__xhan6d0.Navbar_navbar_kind_floating__xhan6d3.Navbar_container__xhan6d4 &`
Where as, it should be 
`.Navbar_navbar_kind_floating__xhan6d3 &`

Otherwise, you can refactor as
```ts
const kindVariant = styleVariants({ floating: {}, docked: {} })

const container = style( {
	selectors: {
		[`.${kindVariant.floating} &`]: { /* styles */}
	}
} )


```


Ideally, the `runtimeFn` should allow access variant classes as `styleVariants()`.
E.g -
```ts
const fn = recipe( {
	variants: { size: { sm: {}, md: {}, lg: {} },
	color: { neutral: {}, accent: {} } 
} )

typeof fn.size.sm === 'string' // true
typeof fn.size.sm === 'string' // true
typeof fn.size.sm === 'string' // true
typeof fn.color.neutral === 'string' // true
typeof fn.color.accent === 'string' // true
```

**Comment by graup** [comment]
Btw, there is a workaround for this. You can make a new singular class and add that to the recipe:

```ts
const navbarBase = style({});
const navbar = recipe({
  base: [navbarBase],
  variants: ...
});
export const container = style({
  ...
  selectors: {
    [`${navbarBase} &`]: {
      ...
    },
  },
})
```

But I agree that a way to access the generated variant classes could be useful.
