### ISSUE TITLE
Filter out period from token names

### ISSUE THREAD

**Issue by joshferrell** [vanilla-extract-css/vanilla-extract#950]
### Describe the bug

When generating a css variable when a theme token name contains a period, the css variable becomes invalid. The use case for this is that I'd like to have these tokens:

```
const theme = createTheme({
 space: {
   none: '0rem',
   0: '0rem',
   0.125: '0.125rem',
   0.25: '0.25rem',
   0.5: '0.5rem'
 }
})
```

In the below screenshot, the variable names match with what vanilla-extract is using and what is set in the global variables, but it isn't applied [since periods aren't valid in CSS variable names](https://www.w3.org/TR/CSS22/syndata.html#value-def-identifier). Ideally, token names should be escaped in some way.

<img width="331" alt="Screen Shot 2022-12-13 at 10 44 39 PM" src="https://user-images.githubusercontent.com/19213986/207525214-e2e2c1f1-9b68-444f-a4b0-78cb6932cf93.png">

### Reproduction

https://codesandbox.io/s/vanilla-extract-half-nnd8p8?file=/src/App.css.ts

### System Info

```shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 5.24 GB / 125.72 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  npmPackages:
    @vanilla-extract/css: 1.9.2 => 1.9.2
    @vanilla-extract/sprinkles: ^1.5.1 => 1.5.1
    @vanilla-extract/webpack-plugin: ^2.2.0 => 2.2.0
    webpack: ^5.36.1 => 5.75.0
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rothsandro** [comment]
The period in the custom property is already escaped with `\` for both, the definition and the usage, as shown in your screenshot. And the padding is applied, so it works.

But seems like a bug in the DevTools that it shows "... not set" for escaped custom properties.

**Comment by joshferrell** [comment]
Ah yes you're right, it appears that this is an issue with firefox dev tools. I made a simple codepen example demoing the issue: https://codepen.io/joshferrell/pen/vYappdQ

Chrome dev tools show the right value.
