### ISSUE TITLE
Using with next js v 13, rendering a server component

### ISSUE THREAD

**Issue by Svyatoslav16** [vanilla-extract-css/vanilla-extract#951]
### Describe the bug

package.json dependencies:
![image](https://user-images.githubusercontent.com/44878382/208238508-7905f644-ffa0-43a8-9512-16a644934906.png)

I get this error during development and assembly
![image](https://user-images.githubusercontent.com/44878382/208238590-16d4da0c-36cc-48af-b46a-025621b114df.png)

Also, I understand that next js v 13 is still under development, but I would like to point this out straight away

### Reproduction

without-link

### System Info

```shell
node version 18.10.0
```

### Used Package Manager

yarn

### Logs

```shell
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3929341355'
}
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nevnein** [comment]
I've been trying to get this to work for a while to no avail, here's a codesandbox with a minimal setup if anyone wants to toy around https://codesandbox.io/p/sandbox/vigorous-lamarr-e8pnf4
