### ISSUE TITLE
Cannot install `@vanilla-extract/next-plugin` on Ubuntu LTS

### ISSUE THREAD

**Issue by arturmuller** [vanilla-extract-css/vanilla-extract#953]
### Describe the bug

Cannot install `@vanilla-extract/next-plugin` on Ubuntu LTS. This fails even in a completely fresh repo (see the minimal [repro](https://github.com/arturmuller/vanilla-repro)).

`@vanilla-extract/css` installs fine, but other plugins also fail (tried rollup, webpack, esbuild).

### Reproduction

https://github.com/arturmuller/vanilla-repro

### System Info

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
  Memory: 4.77 GB / 15.55 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
```

### Used Package Manager

`npm` (also tried with `pnpm` with the exact same result)

### Logs

The npm log is too long to fit into the max length of a GitHub issue, but can be found in full at https://github.com/arturmuller/vanilla-repro/blob/main/2022-12-30T12_49_22_369Z-debug-0.log

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arturmuller** [comment]
Based on some more poking around, this seems to be an issue specifically with `esbuild@0.11.16` which is a dependency of `@vanilla-extract/integration`. If I try to install this version of esbuild in a fresh repo it fails with the same issue.

Latest version of esbuild installs just fine, so bumping that dep would fix this installation problem.

**Comment by cseas** [comment]
I'm facing the same issue with Vanilla Extract webpack and rollup plugins on Ubuntu 22.04.1 LTS. 
Here's the full error log when running npm install:

```text
npm ERR! code 1
npm ERR! path /home/abhijeet/Documents/github/hazel-ui/node_modules/@vanilla-extract/integration/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
```

**Comment by arturmuller** [comment]
> I'd recommend anyone else bumping into this issue to also replace their installed Node. The Snap Store distribution has different permissions from the apt-get distribution which can cause issues with [other libraries](https://github.com/admc/wd/issues/586#issuecomment-541583962) too.

@cseas thanks! That is a really valuable thing to know!
