### ISSUE TITLE
no css files import in bundle when use next.js version 13 app directory(beta)

### ISSUE THREAD

**Issue by igoman2** [vanilla-extract-css/vanilla-extract#964]
### Describe the bug

when i remove pages directory to use app directory instead in next.js 13, random classname apply in element but no css files in bundle and style doesn't work. but it works in pages directory.

Here is example repo.
i use vanilla-extract style in app/page/tsx with classname **style.title**

### Reproduction

https://github.com/igoman2/next13-vanilla-extract

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 96.84 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.4
    Safari Technology Preview: 16.4
  npmPackages:
    @vanilla-extract/css: ^1.9.2 => 1.9.2 
    @vanilla-extract/next-plugin: ^2.1.1 => 2.1.1 

 ~/Desktop/next13-vanilla-extract   main 
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NicoZweifel** [comment]
Could be a duplicate, but maybe you can try some of the things from here #929

**Comment by JackHowa** [comment]
Found an example using app directory beta. Working for me https://github.com/SuttonJack/vanilla-extract-app-dir

I had to force `npm i` for compatibility with next plugin: 

```
anilla-extract-app-dir % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vanilla-extract-app-dir@0.1.0
npm ERR! Found: next@13.3.1-canary.6
npm ERR! node_modules/next
npm ERR!   next@"13.3.1-canary.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@">=12.0.5" from @vanilla-extract/next-plugin@2.1.2
npm ERR! node_modules/@vanilla-extract/next-plugin
npm ERR!   dev @vanilla-extract/next-plugin@"^2.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by askoufis** [comment]
Just tested the reproduction repo with the latest version of the next plugin (v2.3.1) and next 13 (v13.5.6) and the VE style works.
