### ISSUE TITLE
Object literal gets duplicated when sprinkles properties are exported

### ISSUE THREAD

**Issue by ncardeli** [vanilla-extract-css/vanilla-extract#995]
### Description

When the properties passed to `createSprinkles` are exported, the webpack plugin duplicates the object literal with the properties definition (I suspect the same happens with the other plugins).

For example, given the following code:

```ts
export const responsiveProperties = defineProperties({
 // properties, shorthands, conditions, etc
});

export const colorModeProperties = defineProperties({
 // properties, shorthands, conditions, etc
});

export const sprinkles = createSprinkles(
  responsiveProperties,
  colorModeProperties,
);
```

The bundled code will end up looking like:

```js
var responsiveProperties = { /* responsiveProperties definition*/ };
var colorModeProperties = { /* colorModeProperties definition*/ };
var sprinkles = (0,_vanilla_extract_sprinkles_createRuntimeSprinkles__WEBPACK_IMPORTED_MODULE_2__.createSprinkles)({ /* responsiveProperties definition*/ },{ /* colorModeProperties definition*/ });
```

The object literals for `responsiveProperties` and `colorModeProperties` end up duplicated as arguments for `createSprinkles`.

### Steps to reproduce the bug

Check the codesandbox link with the minimal reproduction. You can also reproduce by modifying the `webpack-react` example in the `vanilla-extract` repo to export the properties in the `sprinkles.css.ts` file. In both cases, take a look at `dist/main.js` file to see how the object literals end up duplicated.

### Reproduction

https://codesandbox.io/p/sandbox/hardcore-raman-105ni0?file=%2Fsrc%2Fsprinkles.css.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A49%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A4%7D%5D

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 94.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.dev/yarn/v1.22.17/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Firefox: 107.0.1
    Safari: 16.3
  npmPackages:
    @vanilla-extract/babel-plugin: 1.1.7 => 1.1.7
    @vanilla-extract/webpack-plugin: 2.1.11 => 2.1.11
    webpack: 4.46.0 => 4.46.0
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ncardeli** [comment]
I took a look at the code and found that the issue is caused by `stringifyExports` in `@vanilla-extract/integration`. I understand it's a side-effect of how `createSprinkles` gets its arguments through the `args` property of the `__recipe__` object.

Unfortunately I couldn't come up with a great solution to this. However, a possible solution could be to allow devs to specify if the arguments should be serialized with `stringifyExports` or keep it as they are with a `keepArgs` property in the `__function_serializer__` object.

If devs had that possibility, they could override the default behavior and specify the names of the arguments instead of the values:

The code would look like this:

```ts
export const sprinkles = createSprinkles(
  responsiveProperties,
  colorModeProperties,
);

sprinkles.__function_serializer__ = {
  importPath: sprinkles.__recipe__.importPath,
  importName: sprinkles.__recipe__.importName,
  args: ["responsiveProperties", "colorModeProperties"],
  keepArgs: true,
}
```

I'd be interested in contributing to fixing this issue and would love to hear your ideas on how to solve it.

**Comment by mattcompiles** [comment]
Why are you exporting the `responsiveProperties` and `colorModeProperties`?

**Comment by ncardeli** [comment]
In my case, I have two sets of properties. One with conditions and there other without conditions (lets call them `properties` and `conditionalProperties`.

I need the two objects to know:

1. What properties a shorthand property is mapped to. I use `properties.styles[property].mappings` and `conditionalProperties.styles[property].mappings` for that.
2. if a given property has conditions or not. I check for `conditionalProperties.styles[property]`.

With that information I make some decisions to transform a complex data structure into atomic classes accepted by my sprinkles function. The complex data structure is a structure we use to specify values for different conditions like screen size or interactive states like if a component is hovered or focused for React component's props.

Think of something like this to specify different colors for different interactive states:

```jsx
<Component color={{
    defaultValue: 'color1', 
    conditions: [
      { 
        condition: {hover: true}, 
        value: 'color2'
      },
      { 
        condition: {focus: true}, 
        value: 'color3'
      },
    ]
  }}
/>
```

This structure is then mapped to something like:

```js
sprinkles({
  color: {
    base: 'color1',
    hover: 'color2',
    focus: 'color3',
  }
})
```

**Comment by markdalgleish** [comment]
As a workaround, it might be a good idea to use `@vanilla-extract/sprinkles/createRuntimeSprinkles` yourself rather than relying on function serialization. This way you have full control over all serialized exports and don't accidentally serialize the arguments twice. The only real downside is that you need to split your Sprinkles setup code into two files. I haven't tried this myself, but this _should_ work.

```ts
// sprinkles.css.ts
export const responsiveProperties = defineProperties({
 // properties, shorthands, conditions, etc
});

export const colorModeProperties = defineProperties({
 // properties, shorthands, conditions, etc
});
```

```ts
// sprinkles.ts
import { createSprinkles } from '@vanilla-extract/sprinkles/createRuntimeSprinkles';
import { responsiveProperties, colorModeProperties } from './sprinkles.css';

export { responsiveProperties, colorModeProperties };

export const sprinkles = createSprinkles(
  responsiveProperties,
  colorModeProperties,
);
```

**Comment by ncardeli** [comment]
The workaround works like a charm @markdalgleish! Thank you!
